Failing tests for Psych::DisallowedClass:
TuftsUniversity/tufts-spotlight pull request #25
Opened 2023-02-08 14:21 UTC by rawOrlando

```
Psych::DisallowedClass:
        Tried to load unspecified class: Symbol
```

I ran `bundle update` which updated the packages that were not pinned. This seemed fixed some connection issues in the tests. And got farther to hit this error. If these new packages are causing the problem we should pin them. If not one of theses fixed my issue with tests that used js

```
Failure/Error:       driver.browser.file_detector = lambda do |argss|         str = argss.first.to_s         str if File.exist?(str)       end     Net::ReadTimeout:       Net::ReadTimeout with #<TCPSocket:(closed)>
```

2023-02-09 14:13 UTC, rawOrlando commented on .github/workflows/ci.yml
> +        ruby-version: ['2.7']
wow 👀, the image was already 2.7 so will we need to heavily test this change?

2023-02-09 14:31 UTC, mkorcy commented on .github/workflows/ci.yml
> +        ruby-version: ['2.7']
One of the changes you made to Gemfile.lock required 2.7, so I had to bump it here.

2023-02-09 14:35 UTC, mkorcy commented on .github/workflows/ci.yml
> +        ruby-version: ['2.7']
If I remember correctly it was the nokogiri upgrade.

2023-03-15 18:48 UTC, rawOrlando commented
hmmmm I some how broke how the tests were running.

2023-03-28 16:17 UTC, rawOrlando commented
Sari has looked at this in dev, and thinks it looks good.

> Without building a whole new exhibit, all major functions appear to be working as expected!

2023-04-04 15:49 UTC, mkorcy commented
I renamed the PR, it was driving me nuts.

2023-04-04 15:51 UTC, mkorcy requested changes
Only a few comments for an addition of a comment, I searched through all the code in a checked out version to try to find any potential frozen string literal issues which we've had problems with but don't see any, things looking generally good here.

2023-04-04 15:51 UTC, mkorcy commented on config/environments/development.rb
> +  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, HashWithIndifferentAccess]
Can you add a comment here about why we had to do this?  I feel like in the middle of these other changes we'll look back on this confused

2023-04-04 15:51 UTC, mkorcy commented on config/environments/production.rb
> +  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, HashWithIndifferentAccess]
same comment as previous

2023-04-04 15:51 UTC, mkorcy commented on config/environments/tdldev.rb
> +  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, HashWithIndifferentAccess]
same comment as last.

2023-04-04 15:51 UTC, mkorcy commented on config/environments/test.rb
> +  config.active_record.yaml_column_permitted_classes = [Symbol, Hash, HashWithIndifferentAccess]
same comment as last

2023-04-04 15:51 UTC, mkorcy commented on config/initializers/translation.rb
> +  I18n::Backend::ActiveRecord.include I18n::Backend::Memoize
Whats the premise of making this change?

2023-04-04 15:51 UTC, mkorcy commented on lib/tasks/test.rake
> +        Rails.root.join("config/#{f}.yml.sample"),
The point of the join here is not to have the path separator in the expression, I'm guessing rubocop did this its a little weird. Rails.root.join('config',"#{f}.yml.sample") may be preferred? I'm not sure, I don't feel particularly strongly either way. probably fine to leave as is.

2023-04-04 15:51 UTC, mkorcy commented on spec/features/feature_page_customizations_spec.rb
> +  scenario "In menu' checkbox exists in form, and sets value in db" do
again minor, I think 'In menu' is intentionally quoted here.

2023-04-04 15:51 UTC, mkorcy commented on spec/helpers/spotlight_helper_spec.rb
> +  let(:link) { "<a target=\"_blank\" rel=\"noopener\" href=\"test.com\">Click to view object</a>" }
what happened here? why the rel attribute addition?

2023-04-05 19:57 UTC, rawOrlando commented on spec/helpers/spotlight_helper_spec.rb
> +  let(:link) { "<a target=\"_blank\" rel=\"noopener\" href=\"test.com\">Click to view object</a>" }
https://www.rubydoc.info/gems/rubocop-rails/RuboCop/Cop/Rails/LinkToBlank
This was following rubicon recommendations.

2023-04-06 13:16 UTC, rawOrlando commented on lib/tasks/test.rake
> +        Rails.root.join("config/#{f}.yml.sample"),
rubicon here wanted to change an unless to a next if. but your point about rails join is well received

2023-04-06 13:21 UTC, rawOrlando commented on spec/helpers/spotlight_helper_spec.rb
> +  let(:link) { "<a target=\"_blank\" rel=\"noopener\" href=\"test.com\">Click to view object</a>" }
The change is also in [app/helpers/spotlight_helper.rb](https://github.com/TuftsUniversity/tufts-spotlight/pull/25#diff-7e456ab3da93bc5265fa5341069e9915163669724946debf6b677fde240e5488)

2023-04-07 18:01 UTC, mkorcy approved these changes
👍

2023-04-07 18:09 UTC, merged